# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f06883e0e39518e54b4c1f9cad46852069774a0f21173617c4d97cbe86f8b598e1b4dc3b61bf1f55466ecfafd3f8e1e5bc4f2fa77a0764fd8de6c09e7280e9

test:
  secret_key_base: a80b1d5d4a0f8631d4288dda4b883bc924c13009a9265d1d64317c5cfccd78c779486be07d7beb9e2184fe9101f94b6d70559c08d0d42c84106409b03dd1db59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 90ff41771a84b255bef3780cffb1f2c131af52d4e90458f203b38c5b7844f4bdf09d6159a2f747157f2bbe782fae0d42ffe4d341863f89b8ca0938ad1774ca43